# Configuração do Projeto
site_name: Projeto Monitores IBMEC
site_url: https://projetos-de-extensao.github.io/PFE_25.2_8002_V
site_author: PFE_25.2_8002_V
site_description: 
  Documentação do projeto de desenvolvimento frontend para a plataforma 
  de monitores da faculdade IBMEC.

# Repositório
repo_name: PFE_25.2_8002_V 
repo_url: https://github.com/Projetos-de-Extensao/PFE_25.2_8002_V.git

copyright: Copyright &copy; 2025 - PFE_25.2_8002_V

# Configuração do Tema
theme:
  name: material
  language: pt
  palette:
    # Paleta para modo claro
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Mudar para modo escuro
    # Paleta para modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs # Navegação em abas
    - navigation.sections # Seções expansíveis no menu lateral
    - toc.integrate # Integra o índice da página no menu lateral
    - navigation.top # Botão para voltar ao topo
    - search.suggest # Sugestões de busca
    - content.code.annotate # Anotações em blocos de código
    - content.code.copy # Botão para copiar código

# Estrutura de Navegação (Menu)
nav:
  - 'Introdução': 'index.md'
  - 'Concepção do Produto': 
    - 'Termo de Abertura (5W2H)': 'concepcao/termo-de-abertura.md'
    - 'Fluxos de Tarefa': 'concepcao/fluxos-de-tarefa.md'
    - 'Prototipação de Baixo Nível': 'concepcao/prototipacao.md'

  - 'Metodologia':
    - 'Nosso Processo': 'metodologia/processo.md'
    - 'Ferramentas': 'metodologia/ferramentas.md'

# Extensões do Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/